version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Add commands here for dependency installation, if needed
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: .
